### ISSUE TITLE
Failed to initialize WebGL

### ISSUE THREAD

**Issue by marcosh** [vadimbakaev/flatmap.io#94]
**Describe the bug**
As soon as I try to load the page with Firefox, the map is not loaded and I see a `Error: "Failed to initialize WebGL"` message in console

**To Reproduce**
Just load the page

**Expected behavior**
see the map

**Screenshots**
![Screenshot_20200513_123416](https://user-images.githubusercontent.com/2643972/81802326-26250180-9516-11ea-97ff-ef41b136b935.png)

**Desktop (please complete the following information):**
 - OS: ArchLinux
 - Browser: Firefox
 - Version: 75.0

**Comment by vadimbakaev** [comment]
@marcosh Thank you for reporting that!

**Comment by vadimbakaev** [comment]
Hey @marcosh, can you please check on this page if you browser support WebGL? https://browserleaks.com/webgl

**Comment by marcosh** [comment]
That was indeed the problem. Somehow WebGL was not working in my browser. Updating to Firefox 76 solved the issue.

Thanks for the help and sorry for the bother
